spring.application:
  name: example-service

logging:
  level:
    root: INFO
#    root: DEBUG

participant-service:
  base:
    path: http://localhost:8080

security:
  keystore:
    path: #test
    password: #test
  trustStore:
    path: #test
    password: #test

server:
  port: 8081