openapi: 3.0.3
info:
  title: Raffle Service Participation API
  description: API for Raffle Service Participation
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
  contact:
    name: Raffle Service Team
servers:
  - url: http://localhost:8080
    description: local environment
tags:
  - name: participation-service
    description: Access point for participation service
paths:
  /v1/raffle-tool/participation/email/{email}:
    get:
      tags:
        - participation-service
      operationId: getParticipant
      summary: Get participant details for given user email
      description: API for get participant for given user email
      parameters:
        - name: email
          in: path
          required: true
          description: path variable
          schema:
            type: string
      responses:
        '200': #Successful response code
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/participant-get'

        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '400':
          $ref: '#/components/responses/badRequest'
        '500':
          $ref: '#/components/responses/internalServerError'

  /v1/raffle-tool/participation/:
    post:
      tags:
        - participation-service
      operationId: addParticipant
      summary: Post participant info
      description: API for post participant info
      responses:
        '201': #Successful response code
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/participant'

        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '400':
          $ref: '#/components/responses/badRequest'
        '500':
          $ref: '#/components/responses/internalServerError'


components:
  schemas:
    participant:
      type: object
      properties:
        eventId:
          type: string
          example: "raffle-event"
        email:
          type: string
          example: "john_doe@epam.com"
        location:
          type: string
          example: "California"
        status:
          type: string
          example: "Winner"

    participant-get:
      type: object
      properties:
        eventId:
          type: string
          example: "raffle-event"
        email:
          type: string
          example: "john_doe@epam.com"
        location:
          type: string
          example: "California"
        raffleNumber:
          type: integer
          example: "123"
        status:
          type: string
          example: "Winner"

  responses:
    unauthorized:
      description: Unauthorized Exception
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: "User can't be authenticated"
                  code:
                    type: string
                    example: '401'

    forbidden:
      description: Forbidden Exception
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: "Access Denied"
                  code:
                    type: string
                    example: '403'

    internalServerError:
      description: Internal Server Exception
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Application Error Occured. Contact Administrator"
                  code:
                    type: string
                    example: '500'

    notFound:
      description: Entity Not Found Exception
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: "Resource Not Found"
                  code:
                    type: string
                    example: '404'

    badRequest:
      description: Bad Request Exception
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                    example: "Illegal Arguments Passed"
                  code:
                    type: string
                    example: '400'